/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyecto_sistema_venta.Presentacion;
import javax.swing.JOptionPane;
import proyecto_sistema_venta.Entidades.Cliente;
import proyecto_sistema_venta.Negocio.ClienteNegocio;

/** 
 *
 * @author User
 */
public class Frm_Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Cliente
     */
    
    private ClienteNegocio CONTROL;
    private ClienteNegocio doc;
    private String accion;
    private Cliente cliente;
    private String resp;
    private int idcliente;
    
    
    
    public Frm_Cliente() {
        initComponents();
        this.CONTROL = new ClienteNegocio();
        this.doc = new ClienteNegocio();       
        cargarTiposDocumento();
        this.listar("");
        TabCliente.setEnabledAt(0, true);
        TabCliente.setEnabledAt(1, false);
        TabCliente.setSelectedIndex(0);
    }
    
    private void listar(String texto) {
        TblCliente.setModel(this.CONTROL.listar(texto));
    }
    
    private void limpiar() {     
        TxtNumeroDocumento.setText("");
        TxtARazonSocial.setText("");
        TxtTelefono.setText("");
        TxtCorreo.setText("");
        TxtADireccion.setText("");
        CbxTipoDocumento.setSelectedIndex(0);
        ChkEstado.setSelected(false);
        this.accion = "guardar"; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        TabCliente = new javax.swing.JTabbedPane();
        TabListado = new javax.swing.JPanel();
        LblBuscar = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCliente = new javax.swing.JTable();
        TabMantenimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CbxTipoDocumento = new javax.swing.JComboBox<>();
        TxtNumeroDocumento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtARazonSocial = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtADireccion = new javax.swing.JTextArea();
        TxtTelefono = new javax.swing.JTextField();
        TxtCorreo = new javax.swing.JTextField();
        ChkEstado = new javax.swing.JCheckBox();
        BtnGuardar = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Mantenimiento Cliente");
        setName(""); // NOI18N

        LblBuscar.setText("Buscar");

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        TblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblCliente);

        javax.swing.GroupLayout TabListadoLayout = new javax.swing.GroupLayout(TabListado);
        TabListado.setLayout(TabListadoLayout);
        TabListadoLayout.setHorizontalGroup(
            TabListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabListadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(TabListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(TabListadoLayout.createSequentialGroup()
                        .addComponent(LblBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminar)
                        .addGap(0, 196, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TabListadoLayout.setVerticalGroup(
            TabListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabListadoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(TabListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBuscar)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnNuevo)
                    .addComponent(BtnEditar)
                    .addComponent(BtnEliminar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabCliente.addTab("Listado", TabListado);

        jLabel1.setText("Tipo de documento");

        jLabel2.setText("Número de documento");

        jLabel3.setText("Razón Social");

        jLabel4.setText("Dirección");

        jLabel5.setText("Telefono");

        jLabel6.setText("Correo");

        jLabel7.setText("Estado");

        CbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TxtARazonSocial.setColumns(20);
        TxtARazonSocial.setRows(5);
        jScrollPane2.setViewportView(TxtARazonSocial);

        TxtADireccion.setColumns(20);
        TxtADireccion.setRows(5);
        jScrollPane3.setViewportView(TxtADireccion);

        ChkEstado.setText("Activo");

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnCerrar.setText("Cerrar");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabMantenimientoLayout = new javax.swing.GroupLayout(TabMantenimiento);
        TabMantenimiento.setLayout(TabMantenimientoLayout);
        TabMantenimientoLayout.setHorizontalGroup(
            TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabMantenimientoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabMantenimientoLayout.createSequentialGroup()
                        .addComponent(BtnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCerrar))
                    .addComponent(ChkEstado)
                    .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CbxTipoDocumento, 0, 147, Short.MAX_VALUE)
                        .addComponent(TxtNumeroDocumento)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        TabMantenimientoLayout.setVerticalGroup(
            TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabMantenimientoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ChkEstado))
                .addGap(45, 45, 45)
                .addGroup(TabMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnCerrar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        TabCliente.addTab("Mantenimiento", TabMantenimiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        this.listar(this.TxtBuscar.getText());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        this.limpiar();
        TabCliente.setEnabledAt(0, false);
        TabCliente.setEnabledAt(1, true);
        TabCliente.setSelectedIndex(1);
        this.accion = "guardar";
        BtnGuardar.setText("Guardar");
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // Validar que se haya seleccionado un tipo de documento
        if (this.CbxTipoDocumento.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de documento");
            return;
        }
        
        String tipoDocumento = this.CbxTipoDocumento.getSelectedItem().toString();
        String numeroDocumento = this.TxtNumeroDocumento.getText();
        String razonSocial = this.TxtARazonSocial.getText();
        String direccion = this.TxtADireccion.getText();
        String telefono = this.TxtTelefono.getText();
        String email = this.TxtCorreo.getText();
        boolean activo = this.ChkEstado.isSelected();
   
        if (this.accion.equals("guardar")) {        
            resp = this.CONTROL.insertar(tipoDocumento, numeroDocumento, razonSocial, direccion, telefono, email);      
        } else if (this.accion.equals("editar")) {        
            resp = this.CONTROL.actualizar(this.idcliente, tipoDocumento, numeroDocumento, razonSocial, direccion, telefono, email, activo); 
        }
    
        System.out.println("Respuesta de la operación (" + this.accion + "): " + resp);   
        if (resp.equalsIgnoreCase("OK")) {
            String mensaje = (this.accion.equals("guardar"))  ? "Cliente registrado correctamente!" : "Cliente actualizado correctamente!";
            JOptionPane.showMessageDialog(null, mensaje);                           
            this.limpiar();
            this.listar(""); 
            TabCliente.setEnabledAt(0, true);
            TabCliente.setEnabledAt(1, false);
            TabCliente.setSelectedIndex(0);
        } else {        
            JOptionPane.showMessageDialog(null, "Error en la operación de " + this.accion + ": " + resp);
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    
    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        if (TblCliente.getSelectedRowCount() == 1) {
            String id_cliente = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 0));
            String tipo_documento = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 1));
            String numero_documento = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 2));
            String razon_social = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 3));
            String direccion = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 4));
            String telefono = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 5));
            String email = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 6));
            String estado = String.valueOf(TblCliente.getValueAt(TblCliente.getSelectedRow(), 7));
            
            boolean est;
            if (estado.equals("Inactivo")) {
                est = false;
            } else {
                est = true;
            }
            this.idcliente = Integer.parseInt(id_cliente);
            this.CbxTipoDocumento.setSelectedItem(tipo_documento);
            this.TxtNumeroDocumento.setText(numero_documento);
            this.TxtARazonSocial.setText(razon_social);
            this.TxtADireccion.setText(direccion);
            this.TxtTelefono.setText(telefono);
            this.TxtCorreo.setText(email);
            this.ChkEstado.setSelected(est);
            
            TabCliente.setEnabledAt(0, false);
            TabCliente.setEnabledAt(1, true);
            TabCliente.setSelectedIndex(1);
            this.accion = "editar";
            BtnGuardar.setText("Editar");
        }else {
        JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente de la tabla para editar.", "Error de Selección", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.limpiar();
        this.listar("");
        TabCliente.setEnabledAt(0, true);   
        TabCliente.setEnabledAt(1, false);  
        TabCliente.setSelectedIndex(0);     
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int filaSeleccionada = TblCliente.getSelectedRow();
        if (filaSeleccionada >= 0) {   
            String id_cliente_str = String.valueOf(TblCliente.getValueAt(filaSeleccionada, 0));
            String razon_social = String.valueOf(TblCliente.getValueAt(filaSeleccionada, 3));
            String estado = String.valueOf(TblCliente.getValueAt(filaSeleccionada, 7));
            int id_cliente_int = Integer.parseInt(id_cliente_str);
            
            // Verificar si está activo o inactivo
            if (estado.equals("Activo")) {
                int respuesta = JOptionPane.showConfirmDialog(
                    this, 
                    "¿Deseas realmente DESACTIVAR el cliente: " + razon_social + "?\n(Se marcará como Inactivo y no se podrá usar en nuevas ventas)", 
                    "Desactivar Cliente", 
                    JOptionPane.YES_NO_OPTION);
            
                if (respuesta == JOptionPane.YES_OPTION) { 
                    resp = this.CONTROL.desactivar(id_cliente_int); 
                    if (resp.equalsIgnoreCase("OK")) {
                        JOptionPane.showMessageDialog(null, "Cliente " + razon_social + " DESACTIVADO correctamente.");
                        this.listar(""); 
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al desactivar el cliente: " + resp);
                    }
                }
            } else {
                int respuesta = JOptionPane.showConfirmDialog(
                    this, 
                    "¿Deseas ACTIVAR el cliente: " + razon_social + "?", 
                    "Activar Cliente", 
                    JOptionPane.YES_NO_OPTION);
            
                if (respuesta == JOptionPane.YES_OPTION) { 
                    resp = this.CONTROL.activar(id_cliente_int); 
                    if (resp.equalsIgnoreCase("OK")) {
                        JOptionPane.showMessageDialog(null, "Cliente " + razon_social + " ACTIVADO correctamente.");
                        this.listar(""); 
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al activar el cliente: " + resp);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente de la tabla para desactivar/activar.", "Error de Selección", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void cargarTiposDocumento() {
        CbxTipoDocumento.removeAllItems();
        CbxTipoDocumento.addItem("--SELECCIONE--");

        for (String t : doc.listarTiposDocumento()) {
        CbxTipoDocumento.addItem(t);
        }
        CbxTipoDocumento.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JComboBox<String> CbxTipoDocumento;
    private javax.swing.JCheckBox ChkEstado;
    private javax.swing.JLabel LblBuscar;
    private javax.swing.JTabbedPane TabCliente;
    private javax.swing.JPanel TabListado;
    private javax.swing.JPanel TabMantenimiento;
    private javax.swing.JTable TblCliente;
    private javax.swing.JTextArea TxtADireccion;
    private javax.swing.JTextArea TxtARazonSocial;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtNumeroDocumento;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables

   
   
    
}
