/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto_sistema_venta.Presentacion;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyecto_sistema_venta.Entidades.Cliente;
import proyecto_sistema_venta.Negocio.ClienteNegocio;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/** 
 *
 * @author User
 */
public class Frm_Selecionar_Cliente extends javax.swing.JDialog {

    private final ClienteNegocio CONTROL;
    private Cliente clienteSeleccionado;
    
    /**
     * Creates new form Frm_Selecionar_Cliente
     */
    public Frm_Selecionar_Cliente(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.CONTROL = new ClienteNegocio();
        this.clienteSeleccionado = null;
        this.setLocationRelativeTo(null);
        this.setTitle("Seleccionar Cliente");
        
        // Cargar todos los clientes al inicio
        this.listar("");
        
        // Configurar búsqueda automática al escribir
        configurarBusquedaAutomatica();
    }
    
    /**
     * Configura la búsqueda automática cuando se escriben 3 o más caracteres
     */
    private void configurarBusquedaAutomatica() {
        TxtBuscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = TxtBuscar.getText().trim();
                
                // Buscar automáticamente si hay 3 o más caracteres
                if (texto.length() >= 3) {
                    listar(texto);
                } else if (texto.length() == 0) {
                    // Mostrar todos si se borra el texto
                    listar("");
                }
            }
        });
    }
    
    /**
     * Lista los clientes según el texto de búsqueda
     */
    private void listar(String texto) {
        TblListadoCliente.setModel(this.CONTROL.listar(texto));
    }
    
    /**
     * Obtiene el cliente seleccionado
     */
    public Cliente getClienteSeleccionado() {
        return this.clienteSeleccionado;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblListadoCliente = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar Cliente");

        jLabel1.setText("Buscar (Nombre o Documento):");

        TxtBuscar.setToolTipText("Escriba al menos 3 caracteres para buscar");

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnSeleccionar.setText("Seleccionar");
        BtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarActionPerformed(evt);
            }
        });

        TblListadoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblListadoCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BtnBuscar)
                .addGap(97, 97, 97)
                .addComponent(BtnSeleccionar)
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnSeleccionar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listado", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        this.listar(TxtBuscar.getText());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarActionPerformed
        if (TblListadoCliente.getSelectedRowCount() == 1) {
            int fila = TblListadoCliente.getSelectedRow();
            
            // Crear objeto cliente con los datos de la fila seleccionada
            clienteSeleccionado = new Cliente();
            clienteSeleccionado.setId_cliente(Integer.parseInt(TblListadoCliente.getValueAt(fila, 0).toString()));
            clienteSeleccionado.setTipo_documento(TblListadoCliente.getValueAt(fila, 1).toString());
            clienteSeleccionado.setNumero_documento(TblListadoCliente.getValueAt(fila, 2).toString());
            clienteSeleccionado.setRazon_social(TblListadoCliente.getValueAt(fila, 3).toString());
            
            // Cerrar el diálogo
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un cliente de la tabla", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnSeleccionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnSeleccionar;
    private javax.swing.JTable TblListadoCliente;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
