/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyecto_sistema_venta.Presentacion;

 
import proyecto_sistema_venta.Negocio.ProductoNegocio;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author User
 */
public class Frm_Seleccionar_Producto extends javax.swing.JDialog {
    
    private Frm_Venta vista;
    private final ProductoNegocio CONTROL;
    /**
     * Creates new form Frm_Seleccionar_Producto
     */
    public Frm_Seleccionar_Producto(java.awt.Frame parent,Frm_Venta frm, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.vista=frm;
        this.setTitle("Seleccionar Productos para la venta");
        
        this.CONTROL=new ProductoNegocio();     
        this.listar("");
        this.listar("");
        // Configurar búsqueda automática
        configurarBusquedaAutomatica();
        this.setVisible(true);
    }

    
    
     private void listar(String texto){
               
        TblListadoProducto.setModel(this.CONTROL.listar(texto));
        TableRowSorter<javax.swing.table.TableModel> orden = new TableRowSorter<>(TblListadoProducto.getModel());
        TblListadoProducto.setRowSorter(orden);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabListadoProducto = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtBuscarProducto = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblListadoProducto = new javax.swing.JTable();

        jLabel1.setText("Nombre");

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnSeleccionar.setText("Seleccionar");
        BtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarActionPerformed(evt);
            }
        });

        TblListadoProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblListadoProducto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBuscar)
                .addGap(194, 194, 194)
                .addComponent(BtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnSeleccionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabListadoProducto.addTab("Listado", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabListadoProducto)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabListadoProducto)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        this.listar(TxtBuscarProducto.getText());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarActionPerformed
        if (TblListadoProducto.getSelectedRowCount() == 1) {
            // Obtener datos del producto seleccionado
            // Columnas: ID(0), Código(1), Nombre(2), Descripción(3), Tipo(4), Color(5), Talla(6), 
            //           P.Compra(7), P.VentaMayor(8), P.VentaMenor(9), StockMin(10), Estado(11)
            int fila = TblListadoProducto.getSelectedRow();
            int idProducto = Integer.parseInt(TblListadoProducto.getValueAt(fila, 0).toString());
            String codigo = TblListadoProducto.getValueAt(fila, 1).toString();
            String nombre = TblListadoProducto.getValueAt(fila, 2).toString();
            
            // Usar precio de venta menor (columna 9)
            double precioVenta = Double.parseDouble(TblListadoProducto.getValueAt(fila, 9).toString());
            
            // Stock temporal (debería consultarse del inventario por tienda)
            int stock = 100;
            
            // Solicitar cantidad
            String cantidadStr = JOptionPane.showInputDialog(this, 
                "Ingrese la cantidad a vender (Stock disponible: " + stock + "):", 
                "Cantidad", 
                JOptionPane.QUESTION_MESSAGE);
            
            if (cantidadStr != null && !cantidadStr.trim().isEmpty()) {
                try {
                    int cantidad = Integer.parseInt(cantidadStr.trim());
                    
                    // Validar cantidad
                    if (cantidad <= 0) {
                        JOptionPane.showMessageDialog(this, 
                            "La cantidad debe ser mayor a cero", 
                            "Error", 
                            JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    if (cantidad > stock) {
                        JOptionPane.showMessageDialog(this, 
                            "La cantidad no puede ser mayor al stock disponible (" + stock + ")", 
                            "Error", 
                            JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    // Solicitar descuento (opcional)
                    String descuentoStr = JOptionPane.showInputDialog(this, 
                        "Ingrese el descuento para este producto (0 si no aplica):", 
                        "Descuento", 
                        JOptionPane.QUESTION_MESSAGE);
                    
                    double descuento = 0.0;
                    if (descuentoStr != null && !descuentoStr.trim().isEmpty()) {
                        try {
                            descuento = Double.parseDouble(descuentoStr.trim());
                            if (descuento < 0) {
                                descuento = 0.0;
                            }
                        } catch (NumberFormatException e) {
                            descuento = 0.0;
                        }
                    }
                    
                    // Calcular subtotal
                    double subtotal = (cantidad * precioVenta) - descuento;
                    
                    // Agregar producto a la venta
                    vista.agregarProducto(idProducto, codigo, nombre, stock, cantidad, precioVenta, descuento, subtotal);
                    
                    // Cerrar el diálogo
                    this.dispose();
                    
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, 
                        "Debe ingresar un número válido para la cantidad", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un producto de la tabla", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnSeleccionarActionPerformed

    /**
     * Configura la búsqueda automática cuando se escriben 3 o más caracteres
     */
    private void configurarBusquedaAutomatica() {
        TxtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                String texto = TxtBuscarProducto.getText().trim();
                
                // Buscar automáticamente si hay 3 o más caracteres
                if (texto.length() >= 3) {
                    listar(texto);
                } else if (texto.length() == 0) {
                    // Mostrar todos si se borra el texto
                    listar("");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnSeleccionar;
    private javax.swing.JTabbedPane TabListadoProducto;
    private javax.swing.JTable TblListadoProducto;
    private javax.swing.JTextField TxtBuscarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
