/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_sistema_venta.Presentacion;

/**
 *
 * @author irupa
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private javax.swing.JDesktopPane desktopPane;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MniTipoProducto = new javax.swing.JMenu();
        MniColor = new javax.swing.JMenuItem();
        MniProductos = new javax.swing.JMenuItem();
        MniTalla = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MniTienda = new javax.swing.JMenuItem();
        MniCliente = new javax.swing.JMenuItem();
        MniKardex = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        MniSalir = new javax.swing.JMenuItem();
        // New Tienda Menu
        MnuTienda = new javax.swing.JMenu();
        MniListarProductos = new javax.swing.JMenuItem();
        MniRegistrarVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas - Menú Principal");

        MniTipoProducto.setText("Procesos");

        jMenuItem1.setText("Tipo Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MniTipoProducto.add(jMenuItem1);

        MniColor.setText("Color");
        MniColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniColorActionPerformed(evt);
            }
        });
        MniTipoProducto.add(MniColor);

        MniTalla.setText("Talla");
        MniTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniTallaActionPerformed(evt);
            }
        });
        MniTipoProducto.add(MniTalla);

        MniProductos.setText("Productos");
        MniProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniProductosActionPerformed(evt);
            }
        });
        MniTipoProducto.add(MniProductos);

        MniTienda.setText("Tiendas");
        MniTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniTiendaActionPerformed(evt);
            }
        });
        MniTipoProducto.add(MniTienda);

        MniCliente.setText("Clientes");
        MniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniClienteActionPerformed(evt);
            }
        });
        MniTipoProducto.add(MniCliente);

        MniKardex.setText("Kardex");
        MniKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniKardexActionPerformed(evt);
            }
        });
        MniTipoProducto.add(MniKardex);

        jMenuBar1.add(MniTipoProducto);

        // Tienda Menu
        MnuTienda.setText("Tienda");

        MniListarProductos.setText("Listar Productos");
        MniListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniListarProductosActionPerformed(evt);
            }
        });
        MnuTienda.add(MniListarProductos);

        MniRegistrarVenta.setText("Registrar Venta");
        MniRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniRegistrarVentaActionPerformed(evt);
            }
        });
        MnuTienda.add(MniRegistrarVenta);

        jMenuBar1.add(MnuTienda);

        jMenu3.setText("Consultas");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        
        MniSalir.setText("Salir del Sistema");
        MniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniSalirActionPerformed(evt);
            }
        });
        jMenu5.add(MniSalir);
        
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1217, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MniColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniColorActionPerformed
        FrmColor frmColor = new FrmColor();
        desktopPane.add(frmColor);
        frmColor.setVisible(true);
        try {
            frmColor.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniColorActionPerformed

    private void MniProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniProductosActionPerformed
        FrmProductos frmProductos = new FrmProductos();
        desktopPane.add(frmProductos);
        frmProductos.setVisible(true);
        try {
            frmProductos.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniProductosActionPerformed

    private void MniTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniTallaActionPerformed
        FrmTalla frmTalla = new FrmTalla();
        desktopPane.add(frmTalla);
        frmTalla.setVisible(true);
        try {
            frmTalla.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniTallaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmTipoProducto frmTipoProducto = new FrmTipoProducto();
        desktopPane.add(frmTipoProducto);
        frmTipoProducto.setVisible(true);
        try {
            frmTipoProducto.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MniListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniListarProductosActionPerformed
        FrmListarProductos frmListarProductos = new FrmListarProductos();
        desktopPane.add(frmListarProductos);
        frmListarProductos.setVisible(true);
        try {
            frmListarProductos.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniListarProductosActionPerformed

    private void MniRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniRegistrarVentaActionPerformed
        Frm_Venta frmVenta = new Frm_Venta(this);
        desktopPane.add(frmVenta);
        frmVenta.setVisible(true);
        try {
            frmVenta.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniRegistrarVentaActionPerformed

    private void MniTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniTiendaActionPerformed
        FrmTienda frmTienda = new FrmTienda();
        desktopPane.add(frmTienda);
        frmTienda.setVisible(true);
        try {
            frmTienda.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniTiendaActionPerformed

    private void MniKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniKardexActionPerformed
        FrmKardex frmKardex = new FrmKardex();
        desktopPane.add(frmKardex);
        frmKardex.setVisible(true);
        try {
            frmKardex.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniKardexActionPerformed

    private void MniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniClienteActionPerformed
        Frm_Cliente frmCliente = new Frm_Cliente();
        desktopPane.add(frmCliente);
        frmCliente.setVisible(true);
        try {
            frmCliente.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MniClienteActionPerformed

    private void MniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniSalirActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro que desea salir del sistema?",
            "Confirmar Salida",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MniSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MniColor;
    private javax.swing.JMenuItem MniCliente;
    private javax.swing.JMenuItem MniKardex;
    private javax.swing.JMenuItem MniListarProductos;
    private javax.swing.JMenuItem MniProductos;
    private javax.swing.JMenuItem MniRegistrarVenta;
    private javax.swing.JMenuItem MniSalir;
    private javax.swing.JMenuItem MniTalla;
    private javax.swing.JMenuItem MniTienda;
    private javax.swing.JMenu MniTipoProducto;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu MnuTienda;
    // End of variables declaration//GEN-END:variables
}
